version: '3'

services:
# API

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - 127.0.0.1:11113:80
    depends_on:
      elastic:
        condition: service_healthy
    healthcheck:
          test: ["CMD", "wget", "http://localhost:80/health"]
          interval: 5s

# data storage

  elastic:
    container_name: elastic
    build:
      context: ./elastic
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 127.0.0.1:9200:9200
    volumes:
     - ./elastic/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
     - ./elastic/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

# frontend

  website:
    build:
      context: ./website
    container_name: website
    volumes:
      - type: bind
        source: ./website/src
        target: /usr/src/website/src
      - type: bind
        source: ./website/static
        target: /usr/src/website/static
    ports:
      - 127.0.0.1:11115:3000
    links:
      - api